# Common Role - Metadata
---
galaxy_info:
  author: Chikwe Azinge
  description: Common base configuration for all servers
  company: Chikwex Infrastructure

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Amazon
      versions:
        - "2023"
        - "2"
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - system
    - common
    - base
    - linux
    - security
    - ssh
    - ntp
    - users

dependencies: []
