apiVersion: v1
kind: Namespace
metadata:
  name: chikwex-eshopz
  labels:
    app.kubernetes.io/part-of: chikwex-eshopz
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: chikwex-eshopz
# trigger
# trigger
# trigger pipeline
# CI/CD trigger
