# AWS Integration Role - Handlers
---
- name: Restart ssm-agent
  ansible.builtin.service:
    name: amazon-ssm-agent
    state: restarted

- name: Restart cloudwatch-agent
  ansible.builtin.service:
    name: amazon-cloudwatch-agent
    state: restarted

- name: Reload cloudwatch-agent
  ansible.builtin.command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    -s
