# Common Role - Handlers
---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: "{{ 'cron' if ansible_os_family == 'Debian' else 'crond' }}"
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
