---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:eks:cluster-name: chikwex-eshopz-eks
  instance-state-name: running
keyed_groups:
  - key: tags['kubernetes.io/cluster/chikwex-eshopz-eks']
    prefix: eks
compose:
  ansible_host: private_ip_address
