# App Deploy Role - Metadata
---
galaxy_info:
  author: Chikwe Azinge
  description: Application deployment with Git/artifact support and zero-downtime releases
  company: Chikwex Infrastructure

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Amazon
      versions:
        - "2023"
        - "2"
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - deployment
    - application
    - git
    - cicd
    - release

dependencies:
  - role: common

collections:
  - amazon.aws
  - community.general
